O challenge Neonify do HackTheBox foi resolvido usando o Kimi K2.6 via Claude Code com Playwright-CLI instalado no sistema e carregado via skills.
O setup foi simples, Playwright-CLI instalado no OS, skills adicionadas pro modelo saber usar a ferramenta, e o Kimi K2.6 rodando como modelo no Claude Code.
A aplicação roda Ruby (Sinatra + WEBrick 1.6.1) com formulário que reflete input no DOM. Filtro de regex bloqueia caracteres especiais. A vulnerabilidade é SSTI via ERB, mas o caminho até ela exige bypass do filtro.
O modelo mapeou todos os 256 caracteres ASCII, criou scripts Python automatizados pra testar bypasses em massa, identificou que ^ e $ em Ruby ancoram por linha e não por string, testou newline injection com sucesso, e confirmou SSTI com <%= 7*7 %> retornando 49. Até aqui, tudo sozinho.
Na hora de escalar pra RCE com File.read, o modelo travou num problema de encoding. O % do ERB era interpretado pelo Rack como URL encoding malformado, retornando HTTP 400. O modelo tentou multipart, printf, scripts Python, mas não conseguiu encodar o payload corretamente. A solução foi URL-encodar tudo no -d do curl: %0a pro newline, %3C%25%3D pro <%=. O raciocínio de segurança tava certo, o que faltou foi resolver o encoding do transporte HTTP.
A integração com o Claude Code também gerou fricção. O modelo tentou usar BloodHound MCP num challenge web e executou comandos sem sentido no terminal (por exemplo, escrever :x pensando que está em um ambiente Vim). O Claude Code foi otimizado pro Claude, e quando outro modelo roda nele, esses erros de contexto aparecem, um aprendizado importante que obtivemos nesta sessão.
O Playwright-CLI acabou sendo usado só pro reconhecimento inicial. A exploração inteira foi via curl.
O Kimi K2.6 mostrou competência em recon, fuzzing e raciocínio de vulnerabilidade. A limitação nesse caso não foi de segurança, foi de encoding HTTP. E a escolha do agente importa tanto quanto a escolha do modelo.
#pentesting #ai #hacking #programming #hackthebox
